"""Combine everyone's results/emissions_*.csv into results/SUMMARY.md (renders nicely on GitHub)."""
import glob
import os

import pandas as pd

files = sorted(glob.glob("results/emissions_*.csv"))
if not files:
    raise SystemExit("No results yet. Run train.py first.")

frames = []
for f in files:
    df = pd.read_csv(f)
    df["who"] = os.path.basename(f)[len("emissions_"):-len(".csv")]
    frames.append(df)
df = pd.concat(frames, ignore_index=True)

cols = {
    "timestamp": "When",
    "who": "Who",
    "project_name": "Tag",
    "run_id": "Run",
    "duration": "Duration (s)",
    "energy_consumed": "Energy (Wh)",
    "emissions": "CO2eq (g)",
    "cpu_model": "CPU",
    "gpu_model": "GPU",
    "region": "Region",
}
out = df[list(cols)].rename(columns=cols)
out["Run"] = out["Run"].astype(str).str[:8]
out["Duration (s)"] = out["Duration (s)"].round(1)
out["Energy (Wh)"] = (out["Energy (Wh)"] * 1000).round(3)
out["CO2eq (g)"] = (out["CO2eq (g)"] * 1000).round(4)
out["GPU"] = out["GPU"].fillna("none")

by_person = out.groupby("Who")[["Duration (s)", "Energy (Wh)", "CO2eq (g)"]].sum().round(3)

with open("results/SUMMARY.md", "w") as fh:
    fh.write("# Emissions summary\n\n_Generated by `python summarize.py`._\n\n")
    fh.write("## Totals by person\n\n" + by_person.to_markdown() + "\n\n")
    fh.write("## All runs\n\n" + out.to_markdown(index=False) + "\n")

print(by_person)
print("\nWrote results/SUMMARY.md")
